#!/bin/bash
# Generate daily development report

PROJECT_ROOT=$(pwd)
CLAUDE_DIR="$PROJECT_ROOT/.claude"
REPORT_DATE=$(date +%Y-%m-%d)
REPORT_FILE="$CLAUDE_DIR/reports/daily-report-$REPORT_DATE.md"

mkdir -p "$CLAUDE_DIR/reports"

echo "Generating daily report for $REPORT_DATE..."

# Read state files
PROGRESS_FILE="$CLAUDE_DIR/state/progress.json"
PERFORMANCE_FILE="$CLAUDE_DIR/state/performance.json"

if [ ! -f "$PROGRESS_FILE" ]; then
    echo "Error: progress.json not found. Run init-project.sh first."
    exit 1
fi

# Extract metrics using python
cat > "$REPORT_FILE" <<EOF
# Daily Development Report - $REPORT_DATE

## Summary
Generated at: $(date +%H:%M:%S)

## Project Status
EOF

# Read progress.json and append to report
if command -v python3 &> /dev/null; then
    python3 <<PYTHON >> "$REPORT_FILE"
import json
import sys

try:
    with open('$PROGRESS_FILE', 'r') as f:
        progress = json.load(f)

    print(f"- Phase: {progress.get('phase', 'unknown')}")
    print(f"- Completed Tasks: {len(progress.get('completed_tasks', []))}")
    print(f"- In Progress: {len(progress.get('in_progress', []))}")
    print(f"- Pending: {len(progress.get('pending', []))}")
    print(f"- Issues: {len(progress.get('issues', []))}")
    print()

    if progress.get('issues'):
        print("## Current Issues")
        for issue in progress['issues']:
            severity = issue.get('severity', 'unknown')
            desc = issue.get('description', 'No description')
            print(f"- [{severity.upper()}] {desc}")
        print()
except Exception as e:
    print(f"Error reading progress: {e}", file=sys.stderr)
PYTHON
fi

# Read performance.json and append
if command -v python3 &> /dev/null; then
    python3 <<PYTHON >> "$REPORT_FILE"
import json
import sys

try:
    with open('$PERFORMANCE_FILE', 'r') as f:
        perf = json.load(f)

    agents_used = perf.get('agents_used', {})
    total_tokens = perf.get('total_tokens', 0)
    estimated_cost = perf.get('estimated_cost', 0)

    print("## Resource Usage")
    print(f"- Total Tokens: {total_tokens:,}")
    print(f"- Estimated Cost: \${estimated_cost:.2f}")
    print()

    if agents_used:
        print("## Agent Usage")
        print("| Agent | Invocations | Tokens | Model |")
        print("|-------|-------------|--------|-------|")
        for agent, stats in agents_used.items():
            invocations = stats.get('invocations', 0)
            tokens = stats.get('tokens', 0)
            model = stats.get('model', 'unknown')
            print(f"| {agent} | {invocations} | {tokens:,} | {model} |")
        print()
except Exception as e:
    print(f"Error reading performance: {e}", file=sys.stderr)
PYTHON
fi

cat >> "$REPORT_FILE" <<EOF

## Next Steps
- Review pending tasks
- Address any blockers
- Continue with next phase

---
*Report generated by generate-report.sh*
EOF

echo "✓ Report generated: $REPORT_FILE"
cat "$REPORT_FILE"
